package org.sormas.e2etests.steps.web.application.cases;

public enum CaseDetailedTableViewHeaders {
  CASE_ID("CASE ID"),
  EXTERNAL_ID("EXTERNAL ID"),
  EXTERNAL_ID_DE("EXTERNE ID"),
  EXTERNAL_TOKEN("EXTERNAL TOKEN"),
  INTERNAL_TOKEN("EXTERNAL TOKEN"),
  DISEASE("DISEASE"),
  DISEASE_VARIANT("DISEASE VARIANT"),
  CASE_CLASSIFICATION("CASE CLASSIFICATION"),
  OUTCOME_OF_CASE("OUTCOME OF CASE"),
  REINFECTION("REINFECTION"),
  INVESTIGATION_STATUS("INVESTIGATION STATUS"),
  FIRST_NAME("FIRST NAME"),
  LAST_NAME("LAST NAME"),
  SEX("SEX"),
  AGE_AND_BIRTH_DATE("AGE AND BIRTH DATE"),
  POSTAL_CODE("POSTAL CODE"),
  CITY("CITY"),
  STREET("STREET"),
  HOUSE_NUMBER("HOUSE NUMBER"),
  ADDITIONAL_INFORMATION("ADDITIONAL INFORMATION"),
  PRIMARY_PHONE_NUMBER("PRIMARY PHONE NUMBER"),
  NUMBER_OF_EVENTS("NUMBER OF EVENTS"),
  LATEST_EVENT_ID("LATEST EVENT ID"),
  LATEST_EVENT_STATUS("LATEST EVENT TITLE"),
  LATEST_EVENT_TITLE("LATEST EVENT TITLE"),
  DATE_OF_SYMPTOM_ONSET("DATE OF SYMPTOM ONSET"),
  LATEST_COLLECTION_DATE("LATEST COLLECTION DATE"),
  RESPONSIBLE_REGION("RESPONSIBLE REGION"),
  RESPONSIBLE_DISTRICT("RESPONSIBLE DISTRICT"),
  RESPONSIBLE_COMMUNITY("RESPONSIBLE COMMUNITY"),
  HEALTH_FACILITY("HEALTH FACILITY"),
  POINT_OF_ENTRY("POINT OF ENTRY"),
  DATE_OF_REPORT("DATE OF REPORT"),
  QUARANTINE_END("QUARANTINE END"),
  SYMPTOM_JOURNAL_STATUS("SYMPTOM JOURNAL STATUS"),
  FOLLOW_UP_STATUS("FOLLOW-UP STATUS"),
  FOLLOW_UP_UNTIL("FOLLOW-UP UNTIL"),
  VACCINATION_STATUS("VACCINATION STATUS"),
  NUMBER_OF_VISITS("NUMBER OF VISITS"),
  COMPLETENESS("COMPLETENESS"),
  REPORTING_USER("REPORTING USER");

  private final String columnHeader;

  CaseDetailedTableViewHeaders(String columnHeader) {
    this.columnHeader = columnHeader;
  }

  @Override
  public String toString() {
    return this.columnHeader;
  }
}
