language: java
jdk:
  - openjdk8 # FIXME remove after transition period (#2617)
  - openjdk11
before_install:
  - cd sormas-base
install: skip
script:
  - mvn install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
