#! /bin/sh
### BEGIN INIT INFO
# Provides:          payara-sormas
# Required-Start:    postgresql
# Required-Stop:     postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Payara-Server SORMAS v4.1.2.172
### END INIT INFO
# Author: Martin Wahnschaffe <m.wahnschaffe@symeda.de>


GLASSFISH_HOME=${GLASSFISH_HOME:-"/opt/payara-172/glassfish"}
DOMAINS_DIR=${DOMAINS_DIR:-"/opt/domains"}

case "$1" in
start)
    su - glassfish -c "$GLASSFISH_HOME/bin/asadmin start-domain --domaindir $DOMAINS_DIR sormas"
    ;;
stop)
    su - glassfish -c "$GLASSFISH_HOME/bin/asadmin stop-domain --domaindir $DOMAINS_DIR sormas"
    ;;
restart)
    su - glassfish -c "$GLASSFISH_HOME/bin/asadmin restart-domain --domaindir $DOMAINS_DIR sormas"
    ;;
*)
    echo "usage: $0 (start|stop|restart|help)"
esac
