@UI @Sanity @Case @CaseImportExport
Feature: Case import and export tests

  @tmsLink=SORDEV-10042 @env_main
  Scenario: Case custom export test
    When API: I create a new person

    And API: I check that POST call status code is 200
    Then API: I create a new case

    And API: I check that POST call status code is 200
    Given I log in as a Admin User
    And I click on the Cases button from navbar
    Then I filter by CaseID on Case directory page
    And I click on the Export case button
    Then I click on the Custom Case Export button
    And I click on the New Export Configuration button in Custom Case Export popup
    Then I fill Configuration Name field with Test Configuration Name
    And I select specific data to export in Export Configuration
    When I download created custom case export file
    And I delete created custom case export file
    Then I check if downloaded data generated by custom case option is correct

    @tmsLink=SORDEV-10040 @env_main
    Scenario: Case basic export test
      When API: I create a new person
      And API: I check that POST call status code is 200
      Then API: I create a new case
      And API: I check that POST call status code is 200
      Given I log in as a Admin User
      And I click on the Cases button from navbar
      Then I filter by CaseID on Case directory page
      And I click on the Export case button
      Then I click on the Basic Case Export button
      Then I check if downloaded data generated by basic case option is correct

  @tmsLink=SORDEV-6134 @env_de
  Scenario: Test Re-add primary phone number and primary email address to import templates for Case
    Given I log in as a Admin User
    Then I click on the Cases button from navbar
    And I click on the Import button from Case directory
    And I click on the detailed button from import Case tab
    Then I select the "TestCase_ImportPrio_template.csv" CSV file in the file picker
    And I click on the "DATENIMPORT STARTEN" button from the Import Case popup
    Then I click to create new person from the Case Import popup
    And I check that an import success notification appears in the Import Case popup
    Then I close Import Cases form
    And I filter by "TestCase ImportPrio" as a Person's full name on Case Directory Page
    And I click APPLY BUTTON in Case Directory Page
    And I open last created case
    Then I navigate to case person tab
    And I check that Type of Contacts details with Primary telephone as a option is visible on Edit Case Person Page
    And I check that Type of Contacts details with Primary email address as a option is visible on Edit Case Person Page

  @tmsLink=SORDEV-9475 @env_de
  Scenario: Test Add reduced vaccination module to imports for Cases
    Given I log in as a Admin User
    Then I click on the Cases button from navbar
    And I click on the Import button from Case directory
    And I click on the detailed button from import Case tab
    Then I select the "DetailedImport_Case_Vaccination.csv" CSV file in the file picker
    And I click on the "DATENIMPORT STARTEN" button from the Import Case popup
    Then I click to create new person from the Case Import popup
    And I check that an import success notification appears in the Import Case popup
    Then I close Import Cases form
    And I filter by "Gandalf The Ill" as a Person's full name on Case Directory Page
    And I click APPLY BUTTON in Case Directory Page
    And I open last created case
    And I check that number of added Vaccinations is 5 on Edit Case Page
    And I click to edit 1 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "08.02.2022"
    And I check that displayed vaccination name is equal to "Sonstiges"
    And I close vaccination form in Edit Case directory
    And I click to edit 2 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "07.02.2022"
    And I check that displayed vaccination name is equal to "Unbekannt"
    And I close vaccination form in Edit Case directory
    And I click to edit 3 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "06.02.2022"
    And I check that displayed vaccination name is equal to "MRT5500 COVID-19 Impfstoff (Sanofi-GSK)"
    And I close vaccination form in Edit Case directory
    And I click to edit 4 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "05.02.2022"
    And I check that displayed vaccination name is equal to "NVX-CoV2373 COVID-19 Impfstoff (Novavax)"
    And I close vaccination form in Edit Case directory
    And I click to edit 5 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "04.02.2022"
    And I check that displayed vaccination name is equal to "Ad26.COV2.S (Johnson & Johnson)"
    And I close vaccination form in Edit Case directory
    And I click to navigate to next page in Vaccinations tab
    And I check that number of added Vaccinations is 3 on Edit Case Page
    And I click to edit 1 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "03.02.2022"
    And I check that displayed vaccination name is equal to "Vaxzevria Injektionssuspension COVID-19-Impfstoff (AstraZeneca)"
    And I close vaccination form in Edit Case directory
    And I click to edit 2 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "02.02.2022"
    And I check that displayed vaccination name is equal to "COVID-19 Impfstoff Moderna (mRNA-Impfstoff)"
    And I close vaccination form in Edit Case directory
    And I click to edit 3 vaccination on Edit Case page
    Then I check that displayed vaccination date is equal to "01.02.2022"
    And I check that displayed vaccination name is equal to "Comirnaty (COVID-19-mRNA Impfstoff)"
    And I close vaccination form in Edit Case directory

  @tmsLink=SORDEV-7454 @env_de
  Scenario:  Test Add multiple variables to detailed export
    When API: I create a new person

    And API: I check that POST call status code is 200
    Then API: I create a new case

    And API: I check that POST call status code is 200
    Given I log in as a National Language User
    And I click on the Cases button from navbar
    Then I filter by CaseID on Case directory page
    And I click on the Export case button
    When I click on the Detailed Case Export button
    When I check if downloaded data generated by detailed case export is correct

  @tmsLink=SORDEV-7454 @env_de
  Scenario:  Test Add multiple variables to custom export
    When API: I create a new person

    And API: I check that POST call status code is 200
    Then API: I create a new case

    And API: I check that POST call status code is 200
    Given I log in as a National User
    And I click on the Cases button from navbar
    Then I filter by CaseID on Case directory page
    And I click on the Export case button
    Then I click on the Custom Case Export button
    And I click on the New Export Configuration button in Custom Case Export popup
    Then I fill Configuration Name field with Test Configuration Name
    And I select Untersuchungsstatus data to export in existing Export Configuration for Custom Case Export
    And I select Untersuchungsdatum data to export in existing Export Configuration for Custom Case Export
    And I select Folgeschäden data to export in existing Export Configuration for Custom Case Export
    And I select Tätigkeitsverbot data to export in existing Export Configuration for Custom Case Export
    And I select Quarantäne-Informationen data to export in existing Export Configuration for Custom Case Export
    And I select Name der/des verantwortlichen Ärztin/Arztes data to export in existing Export Configuration for Custom Case Export
    And I select Telefonnummer der*des zuständigen Ärztin/Arztes data to export in existing Export Configuration for Custom Case Export
    And I select E-Mail-Adresse der*des verantwortlichen Ärztin/Arztes data to export in existing Export Configuration for Custom Case Export
    And I select Meldender Nutzer data to export in existing Export Configuration for Custom Case Export
    And I select Verantwortlicher Benutzer data to export in existing Export Configuration for Custom Case Export
    Then I click Save Button from Custom Case Export Configuration
    When I download created custom case export file
    When I check if downloaded data generated by custom case export is correct

  @tmsLink=SORDEV-12441 @env_de
  Scenario: Hide citizenship and country of birth in Detailed Case Export file
    Given API: I create a new person

    And API: I check that POST call status code is 200
    Given API: I create a new case

    And API: I check that POST call status code is 200
    Given I log in as a Admin User
    And I click on the Cases button from navbar
    Then I filter by CaseID on Case directory page
    And I click on the Export case button
    When I click on the Detailed Case Export button
    And I check if citizenship and country of birth is not present in Detailed Case export file

  @tmsLink=SORDEV-9789 @env_de
  Scenario: Test health conditions from imported case
    Given I log in as a Admin User
    Then I click on the Cases button from navbar
    And I click on the Import button from Case directory
    And I click on the detailed button from import Case tab
    Then I select the "PreExistingCondition_DetailedImport_Test.csv" CSV file in the file picker
    And I click on the "DATENIMPORT STARTEN" button from the Import Case popup
    Then I click to create new person from the Case Import popup
    And I check that an import success notification appears in the Import Case popup
    Then I close Import Cases form
    And I filter by "Margret Schmitt" as a Person's full name on Case Directory Page
    And I click APPLY BUTTON in Case Directory Page
    And I open last created case
    And I check that "diabetes" Pre-existing condition have "Ja" selected
    And I check that "immunodeficiencyIncludingHiv" Pre-existing condition have "Ja" selected
    And I check that "chronicLiverDisease" Pre-existing condition have "Nein" selected
    And I check that "malignancyChemotherapy" Pre-existing condition have "Unbekannt" selected
    And I check that "chronicPulmonaryDisease" Pre-existing condition have "Ja" selected
    And I check that "chronicKidneyDisease" Pre-existing condition have "Ja" selected
    And I check that "chronicNeurologicCondition" Pre-existing condition have "Ja" selected
    And I check that "cardiovascularDiseaseIncludingHypertension" Pre-existing condition have "Ja" selected