@UI @Sanity @Statistics @UI
Feature: Statistics tab tests

  @tmsLink=SORDEV-5978 @env_main
  Scenario: Add event groups to database export
    Given I log in as a Admin User
    And I click on the Statistics button from navbar
    And I click on the Database Export tab from Statistics directory
    And I click on the Event Groups checkbox from Statistics directory
    Then I click on the Export button from Database Export tab
    And I unzip a downloaded file from Database export
    Then I check if downloaded file generated by Event Groups database export contains required headers

  @#7469 @env_main
  Scenario: Validate Statistics directory layout
    Given I log in as a Admin User
    And I click on the Statistics button from navbar
    And I click on the Add filter button from the Statistics Page
    And I click the Remove Filter Button from the Statistics Page
    When I click the Reset Filter Button from the Statistics Page
    And I select Visualisation type Table from the Statistics Page
    Then I Verify the presence of Rows, Columns, and switch-between Button in the Statistics Page
    And I select Visualisation type Map from the Statistics Page
    Then I Verify the presence of Map Type Regions and Districts buttons in the Statistics Page
    And I select Visualisation type Chart from the Statistics Page
    Then I Verify the presence of Chart Type Column buttons in the Statistics Page
