@UI @Sanity @Statistics @UI
Feature: Statistics tab tests

  @tmsLink=SORDEV-5978 @env_main
  Scenario: Add event groups to database export
    Given I log in as a Admin User
    And I click on the Statistics button from navbar
    And I click on the Database Export tab from Statistics directory
    And I click on the Event Groups checkbox from Statistics directory
    Then I click on the Export button from Database Export tab
    And I unzip a downloaded file from Database export
    Then I check if downloaded file generated by Event Groups database export contains required headers

  @#7469 @env_main
  Scenario: Validate Statistics directory layout
    Given I log in as a Admin User
    And I click on the Statistics button from navbar
    And I click on the Add filter button from the Statistics Page
    And I click the Remove Filter Button from the Statistics Page
    When I click the Reset Filter Button from the Statistics Page
    And I select Visualisation type Table from the Statistics Page
    Then I Verify the presence of Rows, Columns, and switch-between Button in the Statistics Page
    And I select Visualisation type Map from the Statistics Page
    Then I Verify the presence of Map Type Regions and Districts buttons in the Statistics Page
    And I select Visualisation type Chart from the Statistics Page
    Then I Verify the presence of Chart Type buttons from the Statistics Page
    And I select Options Data Displayed Case Count from the Statistics Page
    Then I Verify the presence of Show Zero Values checkbox from the Statistics Page
    And I select Options Data Displayed Case Incidence from the Statistics Page
    Then I Verify the presence of Incidence Divisor Input from the Statistics Page
    Then I Verify the presence of the Generate Button from the Statistics Page

  @#7469 @env_main
  Scenario: Validate Statistics directory database export tab layout
    Given I log in as a Admin User
    And I click on the Statistics button from navbar
    And I click on the Database Export tab from Statistics directory
    And I click on the Select All Button in Database Export tab of Statistics Page
    Then I verify that All Checkboxes are Selected in Database Export tab of Statistics Page
    And I click on the Deselect all Button in Database Export tab of Statistics Page
    Then I verify that All Checkboxes are Deselected in Database Export tab of Statistics Page

  @#7469 @env_main
  Scenario: Statistics report generation flow check
    Given I log in as a Admin User
    And I click on the Statistics button from navbar
    And I click on the Add filter button from the Statistics Page
    And I Select the Attribute Disease from the Statistics Page Filter Section in the Statistics Page
    And I Select the COVID-19 option from the Disease Dropdown in the Statistics Page
    And I select Visualisation type Table from the Statistics Page
    And I click on the Generate Button from the Statistics Page
    Then I Verify the Presence of the Export Button from the Statistics Page
    Then I validate the Results Section displays data for Table in the Statistics Page
    And I select Visualisation type Map from the Statistics Page
    And I click on the Generate Button from the Statistics Page
    Then I validate the Results Section displays data for Map in the Statistics Page
    And I select Visualisation type Chart from the Statistics Page
    And I click on the Generate Button from the Statistics Page
    Then I validate the Results Section displays data for Chart in the Statistics Page
