package org.sormas.e2etests.pojo.api.cases;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Date;
import lombok.Builder;
import lombok.NonNull;
import lombok.Value;

@Builder(toBuilder = true, builderClassName = "Builder")
@Value
@JsonInclude(JsonInclude.Include.NON_NULL)
@NonNull
public class CasePostBody {
  public Date creationDate;
  public Date changeDate;
  public String uuid;
  public boolean pseudonymized;
  public String disease;
  public DiseaseVariant diseaseVariant;
  public String diseaseDetails;
  public String plagueType;
  public String dengueFeverType;
  public String rabiesType;
  public Person person;
  public String epidNumber;
  public Date reportDate;
  public ReportingUser reportingUser;
  public Date regionLevelDate;
  public Date nationalLevelDate;
  public Date districtLevelDate;
  public String caseClassification;
  public String caseIdentificationSource;
  public String screeningType;
  public ClassificationUser classificationUser;
  public Date classificationDate;
  public String classificationComment;
  public String clinicalConfirmation;
  public String epidemiologicalConfirmation;
  public String laboratoryDiagnosticConfirmation;
  public String investigationStatus;
  public Date investigatedDate;
  public String outcome;
  public Date outcomeDate;
  public String sequelae;
  public String sequelaeDetails;
  public Region region;
  public District district;
  public Community community;
  public String facilityType;
  public HealthFacility healthFacility;
  public String healthFacilityDetails;
  public String pregnant;
  public String vaccination;
  public String vaccinationDoses;
  public Date firstVaccinationDate;
  public Date lastVaccinationDate;
  public String vaccinationInfoSource;
  public String vaccineName;
  public String otherVaccineName;
  public String vaccineManufacturer;
  public String otherVaccineManufacturer;
  public String vaccineInn;
  public String vaccineBatchNumber;
  public String vaccineUniiCode;
  public String vaccineAtcCode;
  public String vaccine;
  public String smallpoxVaccinationScar;
  public String smallpoxVaccinationReceived;
  public SurveillanceOfficer surveillanceOfficer;
  public String clinicianName;
  public String clinicianPhone;
  public String clinicianEmail;
  public String notifyingClinic;
  public String notifyingClinicDetails;
  public CaseOfficer caseOfficer;
  public int reportLat;
  public int reportLon;
  public int reportLatLonAccuracy;
  public Hospitalization hospitalization;
  public Symptoms symptoms;
  public EpiData epiData;
  public Therapy therapy;
  public ClinicalCourse clinicalCourse;
  public MaternalHistory maternalHistory;
  public String creationVersion;
  public PortHealthInfo portHealthInfo;
  public String caseOrigin;
  public PointOfEntry pointOfEntry;
  public String pointOfEntryDetails;
  public String additionalDetails;
  public String externalID;
  public String externalToken;
  public boolean sharedToCountry;
  public boolean nosocomialOutbreak;
  public String infectionSetting;
  public String quarantine;
  public String quarantineTypeDetails;
  public Date quarantineFrom;
  public Date quarantineTo;
  public String quarantineHelpNeeded;
  public boolean quarantineOrderedVerbally;
  public boolean quarantineOrderedOfficialDocument;
  public Date quarantineOrderedVerballyDate;
  public Date quarantineOrderedOfficialDocumentDate;
  public String quarantineHomePossible;
  public String quarantineHomePossibleComment;
  public String quarantineHomeSupplyEnsured;
  public String quarantineHomeSupplyEnsuredComment;
  public boolean quarantineExtended;
  public boolean quarantineReduced;
  public boolean quarantineOfficialOrderSent;
  public Date quarantineOfficialOrderSentDate;
  public String postpartum;
  public String trimester;
  public String followUpStatus;
  public String followUpComment;
  public Date followUpUntil;
  public boolean overwriteFollowUpUntil;
  public SormasToSormasOriginInfo sormasToSormasOriginInfo;
  public boolean ownershipHandedOver;
  public int caseIdIsm;
  public String covidTestReason;
  public String covidTestReasonDetails;
  public String contactTracingFirstContactType;
  public Date contactTracingFirstContactDate;
  public String wasInQuarantineBeforeIsolation;
  public String quarantineReasonBeforeIsolation;
  public String quarantineReasonBeforeIsolationDetails;
  public String endOfIsolationReason;
  public String endOfIsolationReasonDetails;
  public String prohibitionToWork;
  public Date prohibitionToWorkFrom;
  public Date prohibitionToWorkUntil;
  public String reInfection;
  public Date previousInfectionDate;
  public ReportingDistrict reportingDistrict;
  public String bloodOrganOrTissueDonated;
  public boolean notACaseReasonNegativeTest;
  public boolean notACaseReasonPhysicianInformation;
  public boolean notACaseReasonDifferentPathogen;
  public boolean notACaseReasonOther;
  public String notACaseReasonDetails;
}
