name: 2 - Change Request
description: Suggest the change of an existing feature.
labels: 'change'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to SORMAS! **Please make sure that your issue complies to our [Contributing guidelines](https://github.com/sormas-foundation/SORMAS-Project/blob/development/docs/CONTRIBUTING.md)** before submitting it.
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Tell us why you want us to change or extend an existing feature. Is there something working differently than you expect it? What can be improved about the way it is currently designed?
    validations:
      required: true
  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      description: Describe how you would like the feature to be changed and the expected outcome of your request. If possible and applicable, provide alternative solutions in case your proposed change can not be implemented in the way you outlined it for any reason.
    validations:
      required: true
  - type: textarea
    id: added-value
    attributes:
      label: Added Value/Benefit
      description: Describe how your proposed change would add value to SORMAS and how implementing it would benefit the software or its users.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a list that describes in as much detail as possible what exactly needs to be done in order to fulfill your request (and, if applicable, also what should explicitely not be done). Use a task list for this purpose because it allows developers to easily document which acceptance criteria have been implemented.
      placeholder: |
        - [ ]
        - [ ]
        - [ ]
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: Information about how the implementation should be handled from a technical perspective. They are usually specified by the developers and can be left empty unless you want to suggest a specific way to implement your request.
    validations:
      required: false
  - type: textarea
    id: mockups
    attributes:
      label: Mockups
      description: If your change request requires non-trivial UI/UX work, please provide visual illustrations of how the result should look like. Depending on the complexity of the request, these can be e.g. edited screenshots, single mockups, or multiple mockups depicting a workflow.
      placeholder: You can attach images by clicking this area to highlight it and then dragging them in.
    validations:
      required: false  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: If there is anything else you want to add to your request, you can put it here.
    validations:
      required: false
