<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create new contactFirst name of contact_7e6168_1</name>
   <tag></tag>
   <elementGuidId>5f1014ef-4ffb-4142-a0de-5d94ba769e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sormasui-1655777373-overlays']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sormasui-1655777373-overlays</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-app sormas sormasui v-overlay-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>This content is announced automatically and does not need to be navigated into.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-relevant</name>
      <type>Main</type>
      <value>additions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Create new contactFirst name of contact person*Last name of contact person*Report dateDisease of source case*Please select the source case for this contact, if knownChoose CaseDate of last contactCase ID in external systemCase or event informationResponsible region*Responsible district*Type of contact - if multiple pick the closest contact proximityTouched fluid of source caseDirect physical contact with source caseManipulation of clothes or other objects of source caseWas in close proximity (1 meter) with source caseWas in same room or house with source caseRelationship with caseDescription of how contact took placeDiscardSaveSelect Source CaseUse the text field below to search for any case in the system you have access to. You can search by name, case ID, external ID or epid number. When you're done, click on &quot;Search Case&quot; to see a list of all cases that match the text that you've entered. Select a case in this list and click on &quot;Confirm&quot; to use the selected case as the contact's source case.Search caseCase IDEPID numberFirst nameLast nameAge And Birth DateDistrictHealth Facility NameDate of reportSexCase classificationOutcome of caseWQV4P7BER-BER-20-376Hildegard von Bingen120BerlinNachos Hospital17/02/2020 00:00FemaleNot yet classifiedNo Outcome YetDiscardConfirm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sormasui-1655777373-overlays&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sormasui-1655777373-overlays']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'gwt-uid-38', '&quot;', ')')])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Under follow-up'])[17]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
