package de.symeda.sormas.api.user;

public enum UserRole {

	SURVEILLANCE_SUPERVISOR,
	SURVEILLANCE_OFFICER,
	INFORMANT,
	CASE_SUPERVISOR,
	CASE_OFFICER,
	CONTACT_SUPERVISOR,
	CONTACT_OFFICER,
}
