package org.sormas.e2etests.steps.web.application.contacts;

public enum ContactsDetailedTableViewHeaders {
  CONTACT_ID("CONTACT ID"),
  EXTERNAL_ID("EXTERNAL ID"),
  EXTERNAL_TOKEN("EXTERNAL TOKEN"),
  INTERNAL_TOKEN("EXTERNAL TOKEN"),
  DISEASE("DISEASE"),
  CONTACT_CLASSIFICATION("CONTACT CLASSIFICATION"),
  CONTACT_STATUS("CONTACT STATUS"),
  FIRST_NAME_OF_CONTACT_PERSON("FIRST NAME OF CONTACT PERSON"),
  LAST_NAME_OF_CONTACT_PERSON("LAST NAME OF CONTACT PERSON"),
  SEX("SEX"),
  AGE("AGE"),
  DISTRICT("DISTRICT"),
  POSTAL_CODE("POSTAL CODE"),
  CITY("CITY"),
  STREET("STREET"),
  HOUSE_NUMBER("HOUSE NUMBER"),
  ADDITIONAL_INFORMATION("ADDITIONAL INFORMATION"),
  PRIMARY_PHONE_NUMBER("PRIMARY PHONE NUMBER"),
  LATEST_EVENT_ID("LATEST EVENT ID"),
  LATEST_EVENT_TITLE("LATEST EVENT TITLE"),
  CONTACT_CATEGORY("CONTACT CATEGORY"),
  TYPE_OF_CONTACT("TYPE OF CONTACT"),
  RELATIONSHIP_WITH_CASE("RELATIONSHIP WITH CASE"),
  FOLLOW_UP_STATUS("FOLLOW-UP STATUS"),
  FOLLOW_UP_UNTIL("FOLLOW-UP UNTIL"),
  VACCINATION_STATUS("VACCINATION STATUS"),
  NUMBER_OF_VISITS("NUMBER OF VISITS"),
  PENDING_TASKS("PENDING TASKS"),
  COMPLETENESS("COMPLETENESS"),
  SOURCE_CASE("SOURCE CASE"),
  REPORTING_USER("REPORTING USER");

  private final String columnHeader;

  ContactsDetailedTableViewHeaders(String columnHeader) {
    this.columnHeader = columnHeader;
  }

  @Override
  public String toString() {
    return this.columnHeader;
  }
}
