#! /bin/sh
### BEGIN INIT INFO
# Provides:          payara-sormas
# Required-Start:    postgresql
# Required-Stop:     postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Payara-Server SORMAS v5
### END INIT INFO


GLASSFISH_HOME=${GLASSFISH_HOME:-"/opt/payara5/glassfish"}
DOMAINS_DIR=${DOMAINS_DIR:-"/opt/domains"}

case "$1" in
start)
    su - payara -c "$GLASSFISH_HOME/bin/asadmin start-domain --domaindir $DOMAINS_DIR sormas"
    ;;
stop)
    su - payara -c "$GLASSFISH_HOME/bin/asadmin stop-domain --domaindir $DOMAINS_DIR sormas"
    ;;
restart)
    su - payara -c "$GLASSFISH_HOME/bin/asadmin restart-domain --domaindir $DOMAINS_DIR sormas"
    ;;
*)
    echo "usage: $0 (start|stop|restart|help)"
esac
