package org.sormas.e2etests.steps.web.application.events;

public enum EventsTableColumnsHeaders {
  CONTACTS_HEADER("CONTACTS"),
  EXTERNAL_TOKEN_HEADER("EXTERNAL TOKEN"),
  INVESTIGATION_STATUS_HEADER("INVESTIGATION STATUS"),
  GROUPS_HEADER("GROUPS"),
  INFORMATION_SOURCE_HEADER("SOURCE OF INFORMATION"),
  REPORTING_USER_HEADER("REPORTING USER"),
  EXTERNAL_ID_HEADER("EXTERNAL ID"),
  REPORT_DATE_HEADER("DATE OF REPORT"),
  EVOLUTION_DATE_HEADER("EVOLUTION DATE"),
  SOURCE_TYPE_HEADER("SOURCE TYPE"),
  IDENTIFICATION_SOURCE_HEADER("EVENT IDENTIFICATION SOURCE"),
  RESPONSIBLE_USER_HEADER("RESPONSIBLE USER"),
  DISTRICT_HEADER("DISTRICT"),
  PENDING_TASKS_HEADER("PENDING TASKS"),
  COMMUNITY_HEADER("COMMUNITY"),
  RISK_LEVEL_HEADER("EPIDEMIOLOGICAL RISK LEVEL"),
  FATALITIES_HEADER("FATALITIES"),
  DISEASE_VARIANT_HEADER("DISEASE VARIANT"),
  INTERNAL_TOKEN_HEADER("INTERNAL TOKEN"),
  CASES_HEADER("CASES"),
  EVENT_DATE_HEADER("DATE OF EVENT"),
  REGION_HEADER("REGION"),
  DISEASE_HEADER("DISEASE"),
  ADDRESS_HEADER("ADDRESS"),
  EVENT_ID_HEADER("EVENT ID"),
  TITLE_HEADER("TITLE"),
  STATUS_HEADER("EVENT STATUS"),
  PARTICIPANTS_HEADER("EVENT PARTICIPANTS"),
  MANAGEMENT_STATUS_HEADER("EVENT MANAGEMENT STATUS");

  private final String columnHeader;

  EventsTableColumnsHeaders(String columnHeader) {
    this.columnHeader = columnHeader;
  }

  @Override
  public String toString() {
    return this.columnHeader;
  }
}
