version: "3.5"
services:
  postgres:
    image: "hzibraunschweig/sormas-postgres:${SORMAS_DOCKER_VERSION}"
    ports:
      - ${DB_PORT}:5432/tcp
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SORMAS_POSTGRES_USER: ${SORMAS_POSTGRES_USER}
      SORMAS_POSTGRES_PASSWORD: ${SORMAS_POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_NAME_AUDIT: ${DB_NAME}
    volumes:
      - /var/lib/postgresql/data
    restart: unless-stopped
