###############################################################################
# SORMAS® - Surveillance Outbreak Response Management & Analysis System
# Copyright © 2016-2020 Helmholtz-Zentrum für Infektionsforschung GmbH (HZI)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
###############################################################################

country.AFG.name=Afghanistani
country.ALB.name=Albania
country.DZA.name=Aljeria
country.AND.name=Andorra
country.AGO.name=Angola
country.ATG.name=Antigua na Barbuda
country.ARG.name=Ajentina
country.ARM.name=Armenia
country.AUS.name=Australia
country.AUT.name=Austria
country.AZE.name=Azerbaijan
country.BHS.name=Bahama
country.BHR.name=Bahraini
country.BGD.name=Bangladesh
country.BRB.name=Barbados
country.BLR.name=Belarusi
country.BEL.name=Ubelgiji
country.BLZ.name=Belize
country.BEN.name=Benini
country.BTN.name=Bhutan
country.BOL.name=Bolivia (Nchi ya Watu Wengi)
country.BIH.name=Bosnia na Herzegovina
country.BWA.name=Botswana
country.BRA.name=Brazil
country.BRN.name=Brunei Darussalam
country.BGR.name=Bulgaria
country.BFA.name=Burkina Faso
country.BDI.name=Burundi
country.CPV.name=Kabo Verde
country.KHM.name=Kambodia
country.CMR.name=Kameruni
country.CAN.name=Kanada
country.CAF.name=Jamhuri ya Afrika ya Kati
country.TCD.name=Chad
country.CHL.name=Chile
country.CHN.name=China
country.COL.name=Kolombia
country.COM.name=Komoro
country.COG.name=Kongo (Brazzaville)
country.COK.name=Visiwa vya Cook
country.CRI.name=Costa Rica
country.HRV.name=Kroeshia
country.CUB.name=Cuba
country.CYP.name=Saiprasi
country.CZE.name=Jamhuri ya Cheki
country.PRK.name=Jamhuri ya Kidemokrasia ya Watu ya Korea
country.COD.name=Jamhuri ya Kidemokrasia ya Kongo
country.DNK.name=Denmaki
country.DJI.name=Jibuti
country.DMA.name=Dominika
country.DOM.name=Jamhuri ya Dominika
country.ECU.name=Ecuador
country.EGY.name=Misri
country.SLV.name=El Salvador
country.GNQ.name=Ginea ya Ikweta
country.ERI.name=Eritrea
country.EST.name=Estonia
country.SWZ.name=Eswatini
country.ETH.name=Ethiopia
country.FJI.name=Fiji
country.FIN.name=Ufini
country.FRA.name=Ufaransa
country.GAB.name=Gabon
country.GMB.name=Gambia
country.GEO.name=Georgia
country.DEU.name=Ujerumani
country.GHA.name=Ghana
country.GRC.name=Ugiriki
country.GRL.name=Greenland
country.GRD.name=Grenada
country.GTM.name=Guatemala
country.GIN.name=Ginea
country.GNB.name=Ginea-Bisau
country.GUY.name=Guyana
country.HTI.name=Haiti
country.HND.name=Honduras
country.HUN.name=Hungari
country.ISL.name=Aislandi
country.IND.name=India
country.IDN.name=Indonesia
country.IRN.name=Iran (Jamhuri ya Kiislamu)
country.IRQ.name=Iraki
country.IRL.name=Ayalandi
country.ISR.name=Israeli
country.ITA.name=Italia
country.CIV.name=Ivory Coast
country.JAM.name=Jamaika
country.JPN.name=Japan
country.JOR.name=Jordan
country.KAZ.name=Kazakhstan
country.KEN.name=Kenya
country.KIR.name=Kiribati
country.KWT.name=Kuwait
country.KGZ.name=Kirigizistan
country.LAO.name=Jamhuri ya Kidemokrasia ya Watu wa Lao
country.LVA.name=Latvia
country.LBN.name=Labanoni
country.LSO.name=Lesotho
country.LBR.name=Liberia
country.LBY.name=Libya
country.LIE.name=Liechtenstein
country.LTU.name=Litwania
country.LUX.name=Luksemburgi
country.MDG.name=Madagaska
country.MWI.name=Malawi
country.MYS.name=Malesia
country.MDV.name=Maldivi
country.MLI.name=Mali
country.MLT.name=Malta
country.MHL.name=Visiwa vya Marshall
country.MRT.name=Mauritania
country.MUS.name=Mauritiusi
country.MEX.name=Meksiko
country.FSM.name=Mikronesia (Nchi za Muungano)
country.MCO.name=Monaco
country.MNG.name=Mongolia
country.MNE.name=Montenegro
country.MAR.name=Moroko
country.MOZ.name=Msumbiji
country.MMR.name=Myanmar
country.NAM.name=Namibia
country.NRU.name=Nauru
country.NPL.name=Nepal
country.NLD.name=Uholanzi
country.NCL.name=Kaledonia Mpya
country.NZL.name=Nyuzilandi
country.NIC.name=Nicaragua
country.NER.name=Niger
country.NGA.name=Nigeria
country.NIU.name=Niue
country.MKD.name=Macedonia Kaskazini
country.NOR.name=Norway
country.OMN.name=Omani
country.PAK.name=Pakistani
country.PLW.name=Palau
country.PAN.name=Panama
country.PNG.name=Papua Guniea Mpya
country.PRY.name=Paragwai
country.PER.name=Peru
country.PHL.name=Ufilipino
country.POL.name=Polandi
country.PRT.name=Ureno
country.PRI.name=Puerto Rico
country.QAT.name=Qatar
country.KOR.name=Jamhuri ya Korea
country.MDA.name=Jamhuri ya Moldova
country.ROU.name=Romania
country.RUS.name=Shirikisho la Urusi
country.RWA.name=Rwanda
country.KNA.name=Saint Kitts na Nevis
country.LCA.name=Saint Lucia
country.VCT.name=Senti Vincenti na Grenadini
country.WSM.name=Samoa
country.SMR.name=San Marino
country.STP.name=Sao Tome na Principe
country.SAU.name=Saudi Arabia
country.SEN.name=Senegal
country.SRB.name=Serbia
country.SYC.name=Seychelles
country.SLE.name=Sierra Leone
country.SGP.name=Singapore
country.SVK.name=Slovakia
country.SVN.name=Slovenia
country.SLB.name=Visiwa vya Solomon
country.SOM.name=Somalia
country.ZAF.name=Afrika Kusini
country.SSD.name=Sudani Kusini
country.ESP.name=Hispania
country.LKA.name=Sri Lanka
country.PSE.name=Nchi ya Palestina
country.SDN.name=Sundani
country.SUR.name=Suriname
country.SWE.name=Uswidi
country.CHE.name=Uswisi
country.SYR.name=Jamhuri ya Kiarabu ya Syria
country.TJK.name=Tajikistan
country.THA.name=Thailand
country.TLS.name=Timor-Leste
country.TGO.name=Togo
country.TKL.name=Tokelau
country.TON.name=Tonga
country.TTO.name=Trinidad na Tobago
country.TUN.name=Tunisia
country.TUR.name=Uturuki
country.TKM.name=Turkmenistan
country.TUV.name=Tuvalu
country.UGA.name=Uganda
country.UKR.name=Ukraine
country.ARE.name=Umoja wa Falme za Kiarabu
country.GBR.name=Ufalme wa Muungano wa Uingereza na Irlandia Kaskazini
country.TZA.name=Jamhuri ya Muungano wa Tanzania
country.USA.name=Marekani
country.URY.name=Urugwai
country.UZB.name=Uzbekistan
country.VUT.name=Vanuatu
country.VAT.name=Jiji la Vatikani
country.VEN.name=Venezuela (Jamhuri ya Bolivariani)
country.VNM.name=Vietnamu