###############################################################################
# SORMAS® - Surveillance Outbreak Response Management & Analysis System
# Copyright © 2016-2020 Helmholtz-Zentrum für Infektionsforschung GmbH (HZI)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
###############################################################################

country.AFG.name=Avganistan
country.ALB.name=Albanija
country.DZA.name=Alžir
country.AND.name=Andora
country.AGO.name=Angola
country.ATG.name=Antigva i Barbuda
country.ARG.name=Argentina
country.ARM.name=Jermenija
country.AUS.name=Australija
country.AUT.name=Austrija
country.AZE.name=Azerbejdžan
country.BHS.name=Bahami
country.BHR.name=Bahrein
country.BGD.name=Bangladeš
country.BRB.name=Barbados
country.BLR.name=Belorusija
country.BEL.name=Belgija
country.BLZ.name=Belize
country.BEN.name=Benin
country.BTN.name=Butan
country.BOL.name=Bolivija (Višenacionalna Država)
country.BIH.name=Bosna i Hercegovina
country.BWA.name=Bocvana
country.BRA.name=Brazil
country.BRN.name=Brunej Darusalam
country.BGR.name=Bugarska
country.BFA.name=Burkina Faso
country.BDI.name=Burundi
country.CPV.name=Kabo Verde
country.KHM.name=Kambodža
country.CMR.name=Kamerun
country.CAN.name=Kanada
country.CAF.name=Centralnoafrička Republika
country.TCD.name=Čad
country.CHL.name=Čile
country.CHN.name=Kina
country.COL.name=Kolumbija
country.COM.name=Komori
country.COG.name=Kongo (Brazavil)
country.COK.name=Kukova Ostrva
country.CRI.name=Kosta Rika
country.HRV.name=Hrvatska
country.CUB.name=Kuba
country.CYP.name=Kipar
country.CZE.name=Češka Republika
country.PRK.name=Demokratska Narodna Republika Koreja
country.COD.name=Demokratska Republika Kongo
country.DNK.name=Danska
country.DJI.name=Džibuti
country.DMA.name=Dominika
country.DOM.name=Dominikanska Republika
country.ECU.name=Ekvador
country.EGY.name=Egipat
country.SLV.name=El Salvador
country.GNQ.name=Ekvatorijalna Gvineja
country.ERI.name=Ertireja
country.EST.name=Estonija
country.SWZ.name=Esvatini
country.ETH.name=Etiopija
country.FJI.name=Fidži
country.FIN.name=Finska
country.FRA.name=Francuska
country.GAB.name=Gabon
country.GMB.name=Gambija
country.GEO.name=Gruzija
country.DEU.name=Nemačka
country.GHA.name=Gana
country.GRC.name=Grčka
country.GRL.name=Grenland
country.GRD.name=Grenada
country.GTM.name=Gvatemala
country.GIN.name=Gvineja
country.GNB.name=Gvineja Bisao
country.GUY.name=Gvajana
country.HTI.name=Haiti
country.HND.name=Honduras
country.HUN.name=Mađarska
country.ISL.name=Island
country.IND.name=Indija
country.IDN.name=Indonezija
country.IRN.name=Iran (Islamska Republika)
country.IRQ.name=Irak
country.IRL.name=Irska
country.ISR.name=Izrael
country.ITA.name=Italija
country.CIV.name=Obala Slonovače
country.JAM.name=Jamajka
country.JPN.name=Japan
country.JOR.name=Jordan
country.KAZ.name=Kazahstan
country.KEN.name=Kenija
country.KIR.name=Kiribati
country.KWT.name=Kuvajt
country.KGZ.name=Kirgistan
country.LAO.name=Narodna Demokratska Republika Laos
country.LVA.name=Letonija
country.LBN.name=Liban
country.LSO.name=Lesoto
country.LBR.name=Liberija
country.LBY.name=Libija
country.LIE.name=Lihtenštajn
country.LTU.name=Litvanija
country.LUX.name=Luksemburg
country.MDG.name=Madagaskar
country.MWI.name=Malavi
country.MYS.name=Malezija
country.MDV.name=Maldivi
country.MLI.name=Mali
country.MLT.name=Malta
country.MHL.name=Maršalska Ostrva
country.MRT.name=Mauritanija
country.MUS.name=Mauricijus
country.MEX.name=Meksiko
country.FSM.name=Mikronezija (Savezne Države)
country.MCO.name=Monako
country.MNG.name=Mongolija
country.MNE.name=Crna Gora
country.MAR.name=Maroko
country.MOZ.name=Mozambik
country.MMR.name=Mijanmar
country.NAM.name=Namibija
country.NRU.name=Nauru
country.NPL.name=Nepal
country.NLD.name=Holandija
country.NCL.name=Nova Kaledonija
country.NZL.name=Novi Zeland
country.NIC.name=Nikaragva
country.NER.name=Niger
country.NGA.name=Nigerija
country.NIU.name=Niue
country.MKD.name=Severna Makedonija
country.NOR.name=Norveška
country.OMN.name=Oman
country.PAK.name=Pakistan
country.PLW.name=Palau
country.PAN.name=Panama
country.PNG.name=Papua Nova Gvineja
country.PRY.name=Paragvaj
country.PER.name=Peru
country.PHL.name=Filipini
country.POL.name=Poljska
country.PRT.name=Portugalija
country.PRI.name=Portoriko
country.QAT.name=Katar
country.KOR.name=Republika Koreja
country.MDA.name=Republika Moldavija
country.ROU.name=Rumunija
country.RUS.name=Ruska Federacija
country.RWA.name=Ruanda
country.KNA.name=Sent Kits i Nevis
country.LCA.name=Sveta Lucija
country.VCT.name=Sveti Vinsent i Grenadini
country.WSM.name=Samoa
country.SMR.name=San Marino
country.STP.name=Sao Tome i Prinsipe
country.SAU.name=Saudijska Arabija
country.SEN.name=Senegal
country.SRB.name=Srbija
country.SYC.name=Sejšeli
country.SLE.name=Sijera Leone
country.SGP.name=Singapur
country.SVK.name=Slovačka
country.SVN.name=Slovenija
country.SLB.name=Solomonska Ostrva
country.SOM.name=Somalija
country.ZAF.name=Južna Afrika
country.SSD.name=Južni Sudan
country.ESP.name=Španija
country.LKA.name=Šri Lanka
country.PSE.name=Država Palestina
country.SDN.name=Sudan
country.SUR.name=Surinam
country.SWE.name=Švedska
country.CHE.name=Švajcarska
country.SYR.name=Sirijska Arapska Republika
country.TJK.name=Tadžikistan
country.THA.name=Tajland
country.TLS.name=Istočni Timor
country.TGO.name=Togo
country.TKL.name=Tokelau
country.TON.name=Tonga
country.TTO.name=Trinidad i Tobago
country.TUN.name=Tunis
country.TUR.name=Turska
country.TKM.name=Turkmenistan
country.TUV.name=Tuvalu
country.UGA.name=Uganda
country.UKR.name=Ukrajina
country.ARE.name=Ujedinjeni Arapski Emirati
country.GBR.name=Ujedinjeno Kraljevstvo Velike Britanije i Severne Irske
country.TZA.name=Ujedinjena Republika Tanzanija
country.USA.name=Sjedinjene Američke Države
country.URY.name=Urugvaj
country.UZB.name=Uzbekistan
country.VUT.name=Vanuatu
country.VAT.name=Država Vatikanskog Grada
country.VEN.name=Venecuela (Bolivarska Republika)
country.VNM.name=Vijetnam