###############################################################################
# SORMAS® - Surveillance Outbreak Response Management & Analysis System
# Copyright © 2016-2020 Helmholtz-Zentrum für Infektionsforschung GmbH (HZI)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
###############################################################################

subcontinent.NORTHERN_AFRICA.name = Severna Afrika
subcontinent.NORTHEAST_AFRICA.name =  Severoistočna Afrika
subcontinent.NORTHWEST_AFRICA.name = Severozapadna Afrika
subcontinent.EASTERN_AFRICA.name =  Eastern Africa
subcontinent.SOUTHERN_AFRICA.name = Južna Afrika
subcontinent.SOUTHEAST_AFRICA.name =  Jugoistočna Afrika
subcontinent.SOUTHWEST_AFRICA.name = Jugozapadna Afrika
subcontinent.WESTERN_AFRICA.name =  Zapadna Afrika
subcontinent.CENTRAL_AFRICA.name = Centralna Afrika

subcontinent.CENTRAL_AMERICA.name = Centralna Amerika
subcontinent.NORTH_AMERICA.name = Severna Amerika
subcontinent.SOUTH_AMERICA.name = Južna Amerika

subcontinent.EASTERN_ASIA.name = Istočna Azija
subcontinent.SOUTHERN_ASIA.name = Južna Azija
subcontinent.SOUTHEAST_ASIA.name = Jugoistočna Azija
subcontinent.SOUTHWEST_ASIA.name = Jugozapadna Azija
subcontinent.MIDDLE_EAST.name = Bliski Istok
subcontinent.CENTRAL_ASIA.name = Centralna Azija

subcontinent.AUSTRALIA.name = Australija (Potkontinent)
subcontinent.OCEANIA.name = Okeanija

subcontinent.CENTRAL_EUROPE.name = Centralna Evropa
subcontinent.NORTHERN_EUROPE.name = Severna Evropa
subcontinent.NORTHEAST_EUROPE.name = Severoistočna Evropa
subcontinent.EASTERN_EUROPE.name = Istočna Evropa
subcontinent.SOUTHERN_EUROPE.name = Južna Evropa
subcontinent.SOUTHEAST_EUROPE.name = Jugoistočna Evropa
subcontinent.WESTERN_EUROPE.name = Zapadna Evropa