<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Case IDEPID numberDiseaseCase classific_28592f</name>
   <tag></tag>
   <elementGuidId>9edd0658-9503-41b3-9388-847de98d394d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sormasui-1655777373']/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div[3]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-grid-tablewrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Case IDEPID numberDiseaseCase classificationOutcome of caseInvestigation statusFirst nameLast nameDistrictHealth Facility NamePoint of entryDate of reportCompletenessWQV4P7BER-BER-20-358COVID-19Not yet classifiedNo Outcome YetInvestigation pendingHildegard von BingenBerlinNachos Hospital17/02/2020 00:0040 %WUBSFPBER-BER-20-356COVID-19Not yet classifiedNo Outcome YetInvestigation pendingjohnmorkosBerlinBerlin Nation Hospital25/03/2020 00:0025 %THZKI4BER-BER-20-355COVID-19Not yet classifiedNo Outcome YetInvestigation pendingJohnpeteBerlinOther health facility - berlin central hospital16/03/2020 00:000 %WZZOULBER-BER-20-354COVID-19Not yet classifiedDeceasedInvestigation pendingAkBerlinHome or other place - Spandau27/03/2020 00:0010 %TNWEK2BER-BER-20-353COVID-19Not yet classifiedNo Outcome YetInvestigation doneMimselDingselBerlinBerlin Nation Hospital21/03/2020 00:0055 %QMD2PZBER-BER-20-350COVID-19Not yet classifiedNo Outcome YetInvestigation pendingTestTestBerlinBerlin Nation HospitalOther seaport - mAIN23/03/2020 00:0015 %WS6RXNNIE-OGS-TRE-20-001COVID-19Not yet classifiedNo Outcome YetInvestigation pendingGONGOLAUDOHEwekoroAbalabi Health Clinic09/03/2020 00:0015 %QI5QVCBER-BER-20-344COVID-19Not yet classifiedNo Outcome YetInvestigation pendingtesttestBerlinBerlin Nation Hospital09/03/2020 08:560 %QMZ5JWBER-BER-20-331COVID-19Not yet classifiedNo Outcome YetInvestigation donestefan scmidtBerlinBerlin Nation Hospital02/03/2020 13:0715 %TNBZSJBER-BER-20-341COVID-19Not yet classifiedNo Outcome YetInvestigation pendingJamesBondBerlinOther health facility - Hildegardis Haus17/02/2020 00:0055 %QGZ7EMBER-BER-20-339COVID-19Not yet classifiedNo Outcome YetInvestigation pendingQuentinTarantinoBerlinBerlin Nation Hospital28/02/2020 12:5850 %UZYCHQBER-BER-20-275COVID-19Not yet classifiedNo Outcome YetInvestigation pendingEberhardZahnlosBerlinOther health facility - alc22/02/2020 00:0040 %</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sormasui-1655777373&quot;)/div[@class=&quot;v-ui valo-menu-responsive v-scrollable&quot;]/div[@class=&quot;v-horizontallayout v-layout v-horizontal v-widget v-has-width v-has-height&quot;]/div[@class=&quot;v-expand&quot;]/div[@class=&quot;v-slot v-slot-sormas-content&quot;]/div[@class=&quot;v-csslayout v-layout v-widget sormas-content v-csslayout-sormas-content v-has-width v-has-height&quot;]/div[@class=&quot;v-verticallayout v-layout v-vertical v-widget v-has-width v-has-height&quot;]/div[@class=&quot;v-expand&quot;]/div[@class=&quot;v-slot v-slot-crud-main-layout&quot;]/div[@class=&quot;v-verticallayout v-layout v-vertical v-widget crud-main-layout v-verticallayout-crud-main-layout v-has-width v-has-height v-margin-top v-margin-right v-margin-bottom v-margin-left&quot;]/div[@class=&quot;v-expand&quot;]/div[@class=&quot;v-slot&quot;]/div[@class=&quot;v-grid v-widget v-has-width v-has-height&quot;]/div[@class=&quot;v-grid-tablewrapper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sormasui-1655777373']/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div[3]/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investigation discarded'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investigation done'])[1]/following::div[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
