name: Open API

env:
  java: 11

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    name: mvn verify
    runs-on: ubuntu-latest

    steps:
      - name: Commit OpenAPI specification files
        uses: actions/checkout@v2
        if: github.event_name == 'push' && github.ref == 'development'
        run: |
          mkdir openapi
          cp sormas-rest/target/swagger.yaml openapi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add openapi
          git commit -m "update openapi specification files"
          git push