---
name: OpenAPI Canary

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Testing on specific branch'
# Disabled until fixing the issue with the diff tool
#  schedule:
    # 2.30 UTC
#    - cron: '30 2 * * *'

jobs:
  canary:
    name: Check for changed spec files
    runs-on: ubuntu-latest
    container: openapitools/openapi-diff

    steps:
      - name: Checkout development branch
        uses: actions/checkout@v6
        with:
          path: head

      - name: Checkout master branch
        uses: actions/checkout@v6
        with:
          ref: master
          path: base

      # --fail-on-incompatible is also possible
      - name: Run OpenAPI Diff for external journal API
        run: |
          java -jar /app/openapi-diff.jar --fail-on-changed base/sormas-rest/swagger.yaml \
          head/sormas-rest/swagger.yaml
          
